### ISSUE TITLE
Error handling in historic_forex()

### ISSUE THREAD

**Issue by DataWookie** [DataWookie/polygon#1]
Error message if no data are returned.

**Comment by JoeFernando** [comment]
Hi Andrew, 
This happens when an incorrect pair is provided, eg: "USD/AUD" instead of "AUD/USD"
Kind regards,
Joe

**Comment by DataWookie** [comment]
Added error handling for invalid pairs. Please test.

**Comment by JoeFernando** [comment]
checked and works as advertised!
Beautiful!
Thank you.

Kind regards,
Joe
