### ISSUE TITLE
function to get "Last Quote for a Currency Pair"

### ISSUE THREAD

**Issue by JoeFernando** [DataWookie/polygon#2]
Hi Andrew,

Could you kindly add an additional function to get "last quote for a currency pair"

Thanks in advance.

Kind regards,
Joe

**Comment by JoeFernando** [comment]
an example of my attempt:

last_quote <- function(currency_pair){
  
  link1 <- "https://api.polygon.io/v1/last_quote/currencies/"
  link2 <- currency_pair
  link3 <- "?"
  link4 <- "apiKey=xxxxxxxxxx"

  url <- paste0(link1, link2, link3, link4)
  
  result <- GET(url) %>% content("text") %>% fromJSON()
  
  result$last %>% t %>%  as.data.frame %>%
    dplyr::mutate(timestamp = timestamp(timestamp)) %>% 
    dplyr::select( -exchange, time = timestamp, everything())
  
}

last_quote("AUD/USD")

**Comment by DataWookie** [comment]
Done.
