### ISSUE TITLE
Change currency pair input style in functions to "AUD/USD" instead of "AUD", "USD"

### ISSUE THREAD

**Issue by JoeFernando** [DataWookie/polygon#3]
Hi Andrew,

* Could I kindly ask for a change in the way the currency pair is input in the function to "AUD/USD" style
* Forex is quoted in this fashion, hence it is habitual and becomes intuitive to use this style 
* It also saves a few characters in key-strokes :)

as an example:
historic_forex("AUD/USD", "2018-02-16", limit = 10)

Thanks in advance.

Kind regards,
Joe

**Comment by DataWookie** [comment]
Done.
