### ISSUE TITLE
last_quote_forex returns only "AUD/USD"

### ISSUE THREAD

**Issue by JoeFernando** [DataWookie/polygon#4]
Hi Andrew,

Tha naughty code appears t be in first line in the function:

last_quote_forex <- function (pair) {
  **from_to = strsplit("AUD/USD", "/")[[1]]**                 
    url = paste("v1/last_quote/currencies", from_to[1], from_to[2], 
        sep = "/")
    url = create_url(url)
    result = GET(url) %>% content("text") %>% fromJSON()
    result$last %>% as_tibble() %>% mutate(timestamp = timestamp(timestamp), 
        pair = pair) %>% select(-exchange) %>% select(time = timestamp, 
        pair, everything())
}

Grateful if you could fix at the earliest.

Kind regards,
Joe

**Comment by DataWookie** [comment]
Removed hard coded symbol. Please check.

**Comment by JoeFernando** [comment]
All good!
Works as advertised!
Thank you so very much!
Kind regards,
Joe
