### ISSUE TITLE
historic_forex / Ability to get data from a particular point in time

### ISSUE THREAD

**Issue by JoeFernando** [DataWookie/polygon#5]
Hi Andrew,

historic_forex("AUD/USD", "2018-02-16") %>% tail
                       time    pair     bid     ask
95  2018-02-16 11:53:37.721 AUD/USD 0.79407 0.79391
96  2018-02-16 11:53:38.171 AUD/USD 0.79403 0.79388
97  2018-02-16 11:53:41.174 AUD/USD 0.79403 0.79387
98  2018-02-16 11:53:41.926 AUD/USD 0.79403 0.79388
99  2018-02-16 11:53:43.127 AUD/USD 0.79405 0.79388
100 2018-02-16 11:53:45.529 AUD/USD 0.79407 0.79390

Please could you include functionality such as:
historic_forex("AUD/USD", "2018-02-16", from =  "2018-02-16 11:53:45.529" ) 

This will then provide the next lot of quotes
The idea is to use the function and to get a stream of quotes

Hope I have explained it in a way that is easy for you to understand.

Thanks in advance.

Kind regards,
Joe

**Comment by DataWookie** [comment]
Hi Joe,

Please can you clarify for me the two temporal arguments to the proposed function? It seems to be that the second argument ("2018-02-16") is redundant, given that the third argument provides the same information but at greater precision.

Or am I misunderstanding the purpose of those two arguments?

Thanks,
Andrew.

**Comment by JoeFernando** [comment]
Hi Andrew,

* You will need both arguments as this is the only way to have continuity of the data one wants to down load
* Maybe, the two arguments could be as two input if it helps
* Let me see if I explain through an example below

#############################################################
Andrew this is what I am trying to get at:

step 1:
historic_forex("AUD/USD", "2018-02-16", 5) 

1 2018-02-16 11:48:10.289 AUD/USD 0.79414 0.79397
2 2018-02-16 11:48:15.693 AUD/USD 0.79414 0.79397
3 2018-02-16 11:48:15.992 AUD/USD 0.79414 0.79397
4 2018-02-16 11:48:20.947 AUD/USD 0.79414 0.79398
5 2018-02-16 11:48:35.957 AUD/USD 0.79414 0.79397


step 2: I want to get the next 5 quotes from the last time - 2018-02-16 11:48:35.957 

historic_forex("AUD/USD", "2018-02-16 11:48:35.957" , 5) 

1  2018-02-16 11:48:35.957 AUD/USD 0.79414 0.79397
2  2018-02-16 11:48:38.809 AUD/USD 0.79413 0.79397
3  2018-02-16 11:48:43.312 AUD/USD 0.79413 0.79397
4  2018-02-16 11:48:47.816 AUD/USD 0.79413 0.79398
5  2018-02-16 11:48:55.471 AUD/USD 0.79415 0.79398

step 3: Now I can analyse the entire time period from "2018-02-16 11:48:10.289" to "2018-02-16 11:48:55.471"

#######################################################
* The API returns only the **first** 10,000 quotes
* Typical result looks as follows:

historic_forex("AUD/USD", "2018-02-16", 10000) %>% tail
9995  2018-02-16 19:54:22.151 AUD/USD 0.79859 0.79842
9996  2018-02-16 19:54:27.405 AUD/USD 0.79860 0.79843
9997  2018-02-16 19:54:33.111 AUD/USD 0.79859 0.79842
9998  2018-02-16 19:54:33.861 AUD/USD 0.79858 0.79841
9999  2018-02-16 19:54:35.963 AUD/USD 0.79865 0.79848
10000 2018-02-16 19:54:38.517 AUD/USD 0.79862 0.79846

* So the data is up to only 19:54 for 16/2
* and I want the rest of the data for the day to analyse the whole day
* Hence, the ability to search "from" date/time becomes important

Does this help explain.

Kind regards,
Joe

**Comment by JoeFernando** [comment]
In thinking about this function, I would like to input as follows:
historic_forex(pair = "AUD/USD",
                     Date = "2016-02-16",
                     Time = 00:00:00:000,                                       (default setting)
                      limit = 10000)                                                 (with 100 being default setting)
##########################################

The problem I face is how do I split it between (a) Date and (b) Time from the returned results in order to do the next download

Let me explain with an example:
##########################################
> x <- historic_forex("AUD/USD", "2018-02-16", 5) 
> x
                                    time    pair            bid     ask
1 2018-02-16 11:48:10.289 AUD/USD 0.79414 0.79397
2 2018-02-16 11:48:15.693 AUD/USD 0.79414 0.79397
3 2018-02-16 11:48:15.992 AUD/USD 0.79414 0.79397
4 2018-02-16 11:48:20.947 AUD/USD 0.79414 0.79398
5 2018-02-16 11:48:35.957 AUD/USD 0.79414 0.79397

> max(x$time)
[1] "2018-02-16 11:48:35.957 AEDT"

* How to separate the date and time
* As I will need these as inputs for the second download

**Comment by DataWookie** [comment]
I've added an `offset` parameter to the `historic_forex()` function.

To get data from midnight UTC:

`historic_forex("AUD/USD", "2018-02-02", limit = 20)`

To get data from midday UTC:

`historic_forex("AUD/USD", "2018-02-02", offset = 43200, limit = 20)`

The offset is in seconds from midnight UTC. I think that this should do what you want.

**Comment by JoeFernando** [comment]
works like magic!
